version: "3.9"
services:
  dataTambang:
    container_name: dataTambang
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    ports:
      - "3306:3306"
    volumes:
      - data-tambang:/var/lib/mysql 
    
  dasboardBackend:
    build: ./backend
    container_name: backend
    image: dasboard-tambang-be:latest
    environment:
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
    ports:
      - "4000:4000"
    volumes:                                 
      - ./backend:/app                       
      - /app/node_modules   
    depends_on:
      - dataTambang
      
  dasboardFrontend:
    build: ./frontend/vite-project
    container_name: frontend
    image: dasboard-tambang-fe:latest
    environment:
      - CHOKIDAR_USEPOLLING=true 
    volumes:
      - ./frontend/vite-project:/app
      - /app/node_modules 
    ports:  
      - "80:5173"  
    depends_on:
      - dasboardBackend
  
volumes:
  data-tambang: